"""empty message

Revision ID: a3f20f7b3ae7
Revises: 
Create Date: 2023-04-03 10:15:12.955643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f20f7b3ae7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('person_nationality',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nationality_id'], ['nationalities.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], )
    )
    op.create_table('phone__number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone__number')
    op.drop_table('person_nationality')
    op.drop_table('person')
    op.drop_table('nationalities')
    # ### end Alembic commands ###
