-- SELECT * FROM items
-- SELECT * FROM items WHERE price > 80
-- SELECT * FROM items WHERE price <= 300
-- SELECT * FROM customers WHERE customer_last_name = 'Smith'
-- SELECT * FROM customers WHERE customer_last_name = 'Jones'
-- SELECT * FROM customers WHERE customer_first_name <> 'Scott'