"""empty message

Revision ID: ed07ee6012b1
Revises: 2d90df835b9b
Create Date: 2023-04-27 12:18:53.745459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed07ee6012b1'
down_revision = '2d90df835b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
