"""empty message

Revision ID: ef635dec3930
Revises: 
Create Date: 2023-04-18 09:11:24.149475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef635dec3930'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('created_in_country', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_in_country'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('categories_films',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('films_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['films_id'], ['film.id'], )
    )
    op.create_table('countries_films',
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('films_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['films_id'], ['film.id'], )
    )
    op.create_table('directors_films',
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('films_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['films_id'], ['film.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('directors_films')
    op.drop_table('countries_films')
    op.drop_table('categories_films')
    op.drop_table('film')
    op.drop_table('director')
    op.drop_table('country')
    op.drop_table('category')
    # ### end Alembic commands ###
